### ISSUE TITLE
Skip missing files

### ISSUE THREAD

**Issue by versvisa** [Sync-my-L2P/Sync-my-L2P#98] opened 2016-07-29 10:55 UTC
The download chokes up if a file is unavailable.

    ERROR 12:52:50.559 An error occurred while downloading the file [...] - server replied: Not Found;

There should be a setting to make the program ignore the error and continue with other files. At the moment you need to remove the missing files manually from the selection.

EDIT This happend while loading from the old `www2.` L2P

**Comment by Sync-my-L2P** [comment] 2016-07-29 12:32
I'm a little bit confused. Normally the current version shouldn't work with the old L2P.
Or does the current API also support old learning rooms?

**Comment by versvisa** [comment] 2016-07-29 13:07
The log says

    INFO  15:04:54.035 This version is up to date  ( 20200 )

About page says `Version 2.2.0`

Yes I can access the old learning rooms, most with no problems. Just one has missing/corrupted files.

**Comment by justin-time** [comment] 2016-08-02 15:33
I can confirm it. I'm also able to access files from the old L2P. It looks like the L2P API supports it, now.

**Comment by auxua** [comment] 2016-08-02 18:57
Hi,

Actually, the API is not working with the old L²P.
What you see there is,we had for some semesters old and new L²P running in parallel (piloting/testing the new one). During this time, most course rooms were existing in both L²Ps. During this time, not all documents, announcements, etc. got synced. The API will not guarantee to give a complete list of files or providing them in any form. So you should use the API for older course rooms. 

Additionally, changes to the API enabling new features or fixing behaviours can always cut the support for the old pilot courses.

Greetings from the API Dev :-)

**Comment by Sync-my-L2P** [comment] 2016-09-02 19:09
Fixed in eedca63c153c4047821a68a4db4d08bb9b09ddd9

**Closed by Sync-my-L2P** 2016-09-02 19:09 UTC
Labels: Bug, in progress
